### ISSUE TITLE
Allow scorer to print percentage score

### ISSUE THREAD

**Issue by jonathanirvings** [ia-toki/tcframe#136]
For scorer, it would be good to be able to print percentage of the score (relative to full score) instead of absolute score.

This would be useful for such problem : 

Print "Possible"/"Impossible" in the first line. If it is possible, print one solution in the second line. You only get 50% of the total score if you only get the first line correct.
Subtask 1 (30 points), Subtask 2 (70 poins).

Currently, the scorer does not know whether to give 15 points or 35 points if the contestant only get the first line correct.

**Comment by jonathanirvings** [comment]
@fushar it seems like this has been implemented?

**Comment by fushar** [comment]
Fixed via #190 and #191.
