### ISSUE TITLE
How to create a random string using tcframe. 

### ISSUE THREAD

**Issue by ivorynoise** [ia-toki/tcframe#165]
I referred [testlib.h ](https://github.com/MikeMirzayanov/testlib). It contains a method rnd.next() but I cannot find such facility with rnd object in tcframe. 

```
#include <tcframe/spec.hpp>
using namespace tcframe;

class ProblemSpec : public BaseProblemSpec {
protected:
    string inp;
    string out;

    void InputFormat() {
        RAW_LINE(inp);
    }

    void OutputFormat() {
        LINE(out);
    }

    void GradingConfig() {
        TimeLimit(1);
        MemoryLimit(64);
    }

    void Constraints() {
        CONS(1 <= inp.size() && inp.size() <= 100); // not sure if it's correct
    }

};

class TestSpec : public BaseTestSpec<ProblemSpec> {
protected:
    void SampleTestCase1() {
        Input({
            "apple"
        });
        Output({
            "apple"
        });
    }

    void TestCases() {
        CASE(inp = rnd.next("[a-zA-Z0-9]{1,1000}")); // shows error because next is not defined
        // CASE(inp=???);
    }
};

```

**Comment by fushar** [comment]
Hi @aggarwaldeepak, thanks for your interest in tcframe!

Unfortunately we don't have such string utilities right now.

However, we've kicked off an alpha project for a framework for random object generation here: https://github.com/afaji/tcrand. It has a string randomizer as described here: https://github.com/afaji/tcrand/wiki/StringRandomizer. As this is still very alpha, use it at your own risk!

Feel free to close if this answers your question.
