### ISSUE TITLE
Problems with TCFRAME_HOME path that contains space

### ISSUE THREAD

**Issue by malfple** [ia-toki/tcframe#169]
Reproduce:

1. Escape the space with \
e.g: `TCFRAME_HOME="~/c++\ projects/tcframe"`
First of all I need to add double quotes because it does not work otherwise (I don't know any other solution)
This causes g++ compiler to complain

2. `TCFRAME_HOME="~/c++ projects/tcframe"`
I had to add double quotes: `alias tcframe="$TCFRAME_HOME/scripts/tcframe"`
but that does not work. Instead, if i copy paste `"$TCFRAME_HOME/scripts/tcframe"` in terminal, it works, but I don't know why.
Anyway, I copy-pasted the g++ command in the build script, but it led to even more errors from g++
( ._.)

I believe it will be good if we can put tcframe into any directory, even those containing spaces

**Comment by fairuzi10** [comment]
1. export TCFRAME_HOME **without** single/double quotes so it become like this `TCFRAME_HOME=~/c++\ projects/tcframe`
2. use single quotes rather than double quotes for aliasing. `alias tcframe='$TCFRAME_HOME/scripts/tcframe'`

Feel free to reply if it doesn't fix your problem.
