### ISSUE TITLE
Subtask -1?

### ISSUE THREAD

**Issue by jonathanirvings** [ia-toki/tcframe#30]
Generating test cases...
    
    [ SAMPLE TEST CASES ]
      XXX_sample_1: FAILED
        Reasons:
        * Satisfies subtask -1 but is not assigned to it

**Comment by fushar** [comment]
Cause: it seems that `Constraints()` method conflicts with `SubtaskX()` methods. Will fix it.

**Comment by jonathanirvings** [comment]
My bad. It seems that I mistakenly read the documentation as "put the common constraints of all subtasks in the Constraints() method", so I used the Constraints() method even though it is a subtask-mode question. My bad....
